apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notifications-gw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notifications-gw
    app.kubernetes.io/part-of: notifications-gw
  name: notifications-gw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: notifications-gw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: notifications-gw
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-notifications-tenant/notifications-gw/notifications-gw@sha256:defd528f13f69486e1819cba3c211e47ae54c29e6734197a05a16130355171c2
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8086
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
